config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :todo_items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'todo_items#index'
  get 'home/destroy_all_completed', as: 'destroy_all_completed_todo_items'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :todo_items
end

app/models/todo_item.rb
# frozen_string_literal: true

class TodoItem < ApplicationRecord
  validates :body, presence: true
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists
  has_many :todo_items, through: :lists
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def destroy_all_completed
    if TodoItem.where(completed: true).empty?
      redirect_to root_url, notice: 'You\'ll need to complete some tasks before you can delete them all'
    else
      TodoItem.where(completed: true).destroy_all
      redirect_to root_url, notice: 'Successfully deleted all completed to-do\'s'
    end
  end
end

app/controllers/todo_items_controller.rb
# frozen_string_literal: true

class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items or /todo_items.json
  def index
    filtered_todos = case params[:completed]
                     when 'true'
                       TodoItem.where(completed: true)
                     when 'false'
                       TodoItem.where(completed: false)
                     else
                       TodoItem.all
                     end

    @todo_items = filtered_todos.sort_by(&:created_at).reverse
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1 or /todo_items/1.json
  def show; end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit; end

  # POST /todo_items or /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to root_url, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1 or /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to root_url, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1 or /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo_item
    @todo_item = TodoItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_item_params
    params.require(:todo_item).permit(:body, :completed)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/todo_items_helper.rb
# frozen_string_literal: true

module TodoItemsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">ToDo List</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    </ul>
    <%= render 'filter_form' %>
    <%= render 'nav_form' %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class='container-fluid'>
      <%= yield %>
    <%= link_to 'Delete all completed tasks', destroy_all_completed_todo_items_path, data: { confirm: 'Are you sure?' } %>
    </div>
  </body>
</html>

app/views/todo_items/_filter_form.html.erb
<%= form_for todo_items_path, :method => 'get' do %>
  <div class='input-group form-inline mr-sm-2'>
    <%= select_tag :completed, options_for_select([['All', 'all'], ['Completed', true], ['Active', false]]), prompt: "Select Filter", class: 'form-control mr-sm-2' %>
    <%= submit_tag 'Filter', class: 'btn btn-outline-success mr-sm-4' %>  
  </div>
<% end %>

app/views/todo_items/_form.html.erb
<%= form_with(model: todo_item) do |form| %>
  <% if todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
        <% todo_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_items/_nav_form.html.erb
<%= form_with(model: @todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
        <% @todo_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-inline my-2 my-lg-0'> 
    <%= f.text_field :body, class: 'form-control mr-sm-2' %>
    <%= f.submit 'Add Todo Item', class: 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form', todo_item: @todo_item %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/index.html.erb
<p id="notice"><%= notice %></p>

<table class='table table-hover table-sm table-bordered'>
  <tbody>
    <% @todo_items.each do |todo_item| %>
        <tr class="<%= todo_item.completed ? 'table-success' : 'table-warning' %>">
        <%# make todo item name be the link to edit this will replace show and edit pages %>
          <td><%= link_to todo_item.body, edit_todo_item_path(todo_item) %></td>
          <td>            
            <center>
              <%= form_for(todo_item) do |f| %>
              <%= f.text_field :body, type: 'hidden' %>
                <% if todo_item.completed %>
                  <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
                  <%= f.submit 'Undo', class: 'btn btn-outline-secondary btn-sm' %>
                <% else %>
                  <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
                  <%= f.submit 'Check off', class: 'btn btn-outline-secondary btn-sm' %>
                <% end %>
              <% end %>
            </center>
          </td>
          <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form', todo_item: @todo_item %>

<%= link_to 'Back', todo_items_path %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @todo_item.body %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_item.completed %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>